name: Super-Linter

# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions

#############################
# Start the job on all push #
#############################
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    #name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # Run Linter against code base 
      - name: Run Super-Linter
        uses: docker://github/super-linter:v3
        env:
          #only on new files to save on time
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master