name: Windows | Linux | macOS Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

#https://dev.to/shofol/run-your-github-actions-jobs-from-a-specific-directory-1i9e
defaults:
  run:
    working-directory: ./Get_Data

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    strategy:
      matrix:
        #os: ['ubuntu-latest', 'windows-latest','macos-latest'] #
        os: ['ubuntu-16.04', 'ubuntu-18.04', 'ubuntu-20.04', 'windows-2016', 'windows-2019', 'macos-latest']
        #Python >= 3.6 required
        python-version: [3.6, 3.7, 3.8]

    #runs-on: windows-2019
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout Code
      uses: actions/checkout@v2

    # Get python
    - name: Get Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python Script
      run: |
        python Generate_Osquery_Data.py 1
      
    - uses: actions/upload-artifact@v2
      with:
        name: csv-output_${{ matrix.os }}_${{ matrix.python-version }}
        path: |
          ./Get_Data/Data/
          ./Get_Data/table_*
    
