name: DeployCI
#https://medium.com/@Keithweaver_/zip-code-base-with-github-actions-for-releases-aca66f530dae
on:
  push:
    branches:
      - master
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    #  with:
    #    fetch-depth: '0'
#    - name: Bump version and push tag
#      uses: anothrNick/github-tag-action@master
#      env:
#        SOURCE: Get_Data
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        REPO_OWNER: Sevickson
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "OsqueryGetData"
        files: Get_Data/*
