name: DeployCI
#https://medium.com/@Keithweaver_/zip-code-base-with-github-actions-for-releases-aca66f530dae
on:
  push:
    branches:
      - master
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "OsqueryGetData_v0.1"
        files: Get_Data/*

    #- uses: svenstaro/upload-release-action@v2
    #  with:
    #    repo_token: ${{ secrets.GITHUB_TOKEN }}
    #    file: Get_Data/*
    #    tag: v1.0 #${{ github.ref }}
    #    overwrite: true
    #    file_glob: true
    #    release_name: OsqueryGetData
