name: TreeBeard

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout Code
      uses: actions/checkout@v2

    # Get python
    - name: Get Python
      uses: actions/setup-python@v2
      
    # Test to check if secrets are correctly imported from ENV  
    #- name: bash #shell
    #  env:
    #    SUPER_SECRET: ${{ secrets.API3_USERNAME }}
    #    SUPER_SECRET1: ${{ secrets.API3_PWD }}
    #    SUPER_SECRET2: ${{ secrets.API1_KEY }}
    #  run: |
    #    echo ${#SUPER_SECRET}
    #    echo ${#SUPER_SECRET1}
    #    echo ${#SUPER_SECRET2}

    # Run TreeBeard
    - name: Run TreeBeard
      uses: treebeardtech/treebeard@master
      with:
        debug: true
      env: 
        API1_KEY: "${{ secrets.API1_KEY }}"
        API3_USERNAME: "${{ secrets.API3_USERNAME }}"
        API3_PWD: "${{ secrets.API3_PWD }}"
        #GRAPHISTRY_API_KEY: ${{ secrets.API1_KEY }}
        #api1_key: ${{ secrets.API1_KEY }}
